
-- CREATING DATABSES ,TABLES
CREATE DATABASE HOSPITAL_MANAGEMENT_SYSTEM;
USE HOSPITAL_MANAGEMENT_SYSTEM;
CREATE TABLE PATIENTS(
PATIENT_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100),
DOB DATE,
GENDER VARCHAR(10) NOT NULL,
PHONE_NUMBER VARCHAR(15) NOT NULL,
LOCATION VARCHAR(100));

CREATE TABLE STAFF(
STAFF_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100),
ROLE VARCHAR(100) NOT NULL,
PHONE_NUMBER VARCHAR(15) NOT NULL,
HIRE_DATE DATE);


CREATE TABLE DEPARTMENTS(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(100) NOT NULL);


CREATE TABLE DOCTORS(
DOCTOR_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
PHONE_NUMBER VARCHAR(15) NOT NULL,
DEPT_ID INT ,
EXPERIENCE INT NOT NULL,
FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID));



CREATE TABLE APPOINTMENTS(
APPOINTMENT_ID INT PRIMARY KEY,
PATIENT_ID INT,
DOCTOR_ID INT,
APP_DATETIME DATETIME,
FOREIGN KEY(PATIENT_ID) REFERENCES PATIENTS (PATIENT_ID),
FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID));



CREATE TABLE TESTS (
  TEST_ID INT PRIMARY KEY,
  APPOINTMENT_ID INT NOT NULL,
  TEST_TYPE VARCHAR(200),
  TEST_DATE DATE,
  FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENTS(APPOINTMENT_ID)
);




CREATE TABLE MEDICAL_RECORDS (
  RECORD_ID INT PRIMARY KEY,
  APPOINTMENT_ID INT NOT NULL,
  DIAGNOSIS VARCHAR(200),
  TREATMENT VARCHAR(200),
  FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENTS(APPOINTMENT_ID)
);



CREATE TABLE BILLS(
BILL_ID INT PRIMARY KEY,
APPOINTMENT_ID INT ,
CONSULTATION_CHARGES INT,
TESTING_CHARGES INT,
OTHER_CHARGES INT,
TOTAL_AMOUNT INT,
PAID_AMOUNT INT,
FOREIGN KEY(APPOINTMENT_ID) REFERENCES APPOINTMENTS(APPOINTMENT_ID));




