-- STRING FUNCTIONS
SELECT CONCAT(FIRST_NAME," ",LAST_NAME) AS FULL_NAME FROM DOCTORS;

SELECT CONCAT(SUBSTRING(FIRST_NAME,1,1),".",LAST_NAME) AS SHORT_NAME FROM DOCTORS;

SELECT UPPER(DEPT_NAME) FROM DEPARTMENTS;

SELECT LOCATION FROM PATIENTS;

SELECT SUBSTRING_INDEX(LOCATION,",",-1) FROM PATIENTS;  

SELECT SUBSTRING_INDEX("TIRUPATHI ANDHRA PREDESH"," ",1);




